DumperWeb/Models/DumperViewModel.cs
namespace DumperWeb.Models
{
    public class DumperViewModel
    {
        public string DumperName { get; set; }
        public List<string> ImageURLs { get; set; }
    }
}

DumperWeb/Models/ErrorViewModel.cs
namespace DumperWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DumperWeb/Controllers/BaseController.cs
using DumperApplicationCore.BusinessLogic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

namespace DumperWeb.Controllers
{
    public class BaseController : Controller
    {
        private readonly DumpAndFetch _manager;
        public BaseController(DumpAndFetch manager)
        {
            _manager = manager;
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            base.OnActionExecuting(context);
        }
    }
}

DumperWeb/Controllers/DumperController.cs
using DumperApplicationCore.BusinessLogic;
using DumperWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace DumperWeb.Controllers
{
    public class DumperController : BaseController
    {
        private readonly IConfiguration _configuration;
        private readonly DumpAndFetch _manager;
        public DumperController(IConfiguration configuration, DumpAndFetch manager) : base(manager)
        {
            _configuration = configuration;
            _manager = manager;
        }

        [Route("Dumper/Within/{dumperName}")]
        public IActionResult InsideDumper(string dumperName)
        {
            if(!_manager.CheckIfDumperNameIsValid(dumperName))
                return RedirectToActionPermanent("Error", "Home");
            
            List<string> imageURLs = _manager.GetImagesOfDumper(dumperName);
            for(int i = 0;i < imageURLs.Count;i++)
            {
                imageURLs[i] = Path.Combine(_configuration.GetValue<string>("ImageDumpLoc"), imageURLs.ElementAt(i));
            }
            return View(model: new DumperViewModel { DumperName = dumperName, ImageURLs = imageURLs});
        }

        public IActionResult GetImageBytes(string imagePathURL)
        {
            byte[] imageBytes = System.IO.File.ReadAllBytes(imagePathURL);
            return new FileContentResult(imageBytes, "image/png");
        }

        public IActionResult InsideDumperBin()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadImagesAsync(List<IFormFile> imageFiles, string dumperName)
        {
            long size = imageFiles.Sum(f => f.Length);

            await _manager.ProcessObjectUploadAsync(imageFiles, _configuration.GetValue<string>("ImageDumpLoc"), dumperName);

            return Ok(new { count = imageFiles.Count, size });
        }
    }
}

DumperWeb/Controllers/HomeController.cs
using DumperApplicationCore.BusinessLogic;
using DumperWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DumperWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly DumpAndFetch _manager;

        public HomeController(ILogger<HomeController> logger, DumpAndFetch manager)
        {
            _logger = logger;
            _manager = manager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateDumper()
        {
            string dumperName = _manager.CreateDumper();
            return Redirect($"~/v/{dumperName}");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DumperWeb/Views/Dumper/InsideDumper.cshtml
@model DumperViewModel
@{
    ViewData["Title"] = "Dumper Bin";
}

<div>
    <p>Paste this URL in the browser to acess this dumper: @Html.ActionLink("Copy URL", "InsideDumper", "Dumper")</p>
</div>

<div id="notificationSection"></div>

<div>
    @Html.AntiForgeryToken()
    <form action="~/Dumper/UploadImages" enctype="multipart/form-data" method="post" onsubmit="UploadFile(this); return false;">
        <div class="file-upload-section">
            <label for="FileUpload_FormFile">Upload Images</label>
            <input id="FileUpload_FormFile" type="file" name="imageFiles" multiple />
            <label for="FileUpload_FormFile"><img src="~/Images/AddButtom.svg" width="32" height="32" /></label>
        </div>
        <input type="text" name="dumperName" value="@Model.DumperName" hidden />
        <input class="submit-button" type="submit" value="Upload" />
        <div>
            <output name="result"></output>
        </div>
    </form>
</div>

<div>
    @{
        if(Model.ImageURLs.Count > 0)
        {
            foreach(string imagePathURL in Model.ImageURLs)
            {
                <text>
                    <img src="@Url.Action("GetImageBytes","Dumper",new {imagePathURL})" height="100" />
                </text>
            }
        }
    }
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/6.0.1/signalr.js"></script>
<script src="~/js/Dumper.js" />
<script>
    async function UploadFile(formElement) {
        var resultElem = formElement.elements.namedItem("result");
        const formData = new FormData(formElement);
        console.log(formData);
        try {
            const response = await fetch(formElement.action, {
                method: 'POST',
                body: formData
            });

            resultElem.value = 'Result is : ' + response.status + ' ' + response.statusText;
        } catch (err) {
            console.log("It's messed up", err);
        }
    }
</script>

DumperWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="welcome-message-wrapper">
    <div class="welcome-message">
        <h2>Welcome to ImageDumper</h2>
        <p>Do you have a lot of images lying around?</p>
        <p>Store them temporarily somewhere without having to sign in!</p>
        <p>Don't ponder since you've got ImageDumper</p>
        @Html.AntiForgeryToken()
        @using (Html.BeginForm("CreateDumper", "Home", FormMethod.Post))
        {
            <input class="submit-button" type="submit" value="Create" />
        }
    </div>
</div>

DumperWeb/Views/Home/InsideDumperBin.cshtml
@{
    ViewData["Title"] = "Dumper Bin";
}

<div>
    <h1>Small Files - Buffered <u>Model Binding</u> to Physical storage</h1>
    <form action="~/Home/UploadImages" enctype="multipart/form-data" method="post" onsubmit="UploadFile(this); return false;">
        <dl>
            <dt>
                <label for="FileUpload_FormFile">File abc</label>
            </dt>
            <dd>
                <input id="FileUpload_FormFile" type="file" name="imageFiles" multiple>
            </dd>
        </dl>
        <input class="btn" type="submit" value="Upload" />
        <div>
            <output name="result"></output>
        </div>
    </form>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<script>
    async function UploadFile(formElement) {
        var resultElem = formElement.elements.namedItem("result");
        const formData = new FormData(formElement);
        console.log(formData);
        try {
            const response = await fetch(formElement.action, {
                method: 'POST',
                body: formData
            });

            resultElem.value = 'Result is : ' + response.status + ' ' + response.statusText;
        } catch (err) {
            console.log("It's messed up", err);
        }
    }
</script>

DumperWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | DumperWeb</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DumperWeb.styles.css" asp-append-version="true" />
</head>
<body>
    @RenderBody()

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DumperWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>